language: generic
sudo: required
services:
 -docker
	
before_install:
 - docker build -t SoumyojitMondal/docker-react -f DOckerfile.dev .

script:
 - docker run -e CI=ture SoumyojitMondal/docker-react npm run test
